#############################################################################
# Makefile for building: opencl
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  opencl.pro
# Template: subdirs
# Command: C:\Qt\5.2.0\mingw48_32\bin\qmake.exe -spec win32-g++ CONFIG+=debug -o Makefile opencl.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.2.0\mingw48_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-src \
		sub-examples \
		sub-demos \
		sub-util \
		sub-tests


sub-src-qmake_all:  FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd src\ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-src-make_first-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-src-make_first: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-src-all-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-src-all: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-src-clean-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-clean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-distclean-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-distclean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-src-install_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-uninstall_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-examples-qmake_all: sub-src-qmake_all FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd examples\ && $(MAKE) -f Makefile qmake_all
sub-examples: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-examples-make_first-ordered: sub-src-make_first-ordered  FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-examples-make_first: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-examples-all-ordered: sub-src-all-ordered  FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-examples-all: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-examples-clean-ordered: sub-src-clean-ordered  FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-examples-clean: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-examples-distclean-ordered: sub-src-distclean-ordered  FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-examples-distclean: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-examples-install_subtargets-ordered: sub-src-install_subtargets-ordered  FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-examples-install_subtargets: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-examples-uninstall_subtargets-ordered: sub-src-uninstall_subtargets-ordered  FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-examples-uninstall_subtargets: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-demos-qmake_all: sub-examples-qmake_all FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd demos\ && $(MAKE) -f Makefile qmake_all
sub-demos: FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-demos-make_first-ordered: sub-examples-make_first-ordered  FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-demos-make_first: FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-demos-all-ordered: sub-examples-all-ordered  FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-demos-all: FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-demos-clean-ordered: sub-examples-clean-ordered  FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-demos-clean: FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-demos-distclean-ordered: sub-examples-distclean-ordered  FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-demos-distclean: FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-demos-install_subtargets-ordered: sub-examples-install_subtargets-ordered  FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-demos-install_subtargets: FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-demos-uninstall_subtargets-ordered: sub-examples-uninstall_subtargets-ordered  FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-demos-uninstall_subtargets: FORCE
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-util-qmake_all: sub-demos-qmake_all FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd util\ && $(MAKE) -f Makefile qmake_all
sub-util: FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-util-make_first-ordered: sub-demos-make_first-ordered  FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-util-make_first: FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-util-all-ordered: sub-demos-all-ordered  FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-util-all: FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-util-clean-ordered: sub-demos-clean-ordered  FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-util-clean: FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-util-distclean-ordered: sub-demos-distclean-ordered  FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-util-distclean: FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-util-install_subtargets-ordered: sub-demos-install_subtargets-ordered  FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-util-install_subtargets: FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-util-uninstall_subtargets-ordered: sub-demos-uninstall_subtargets-ordered  FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-util-uninstall_subtargets: FORCE
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-tests-qmake_all: sub-util-qmake_all FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd tests\ && $(MAKE) -f Makefile qmake_all
sub-tests: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-tests-make_first-ordered: sub-util-make_first-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-tests-make_first: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-tests-all-ordered: sub-util-all-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-tests-all: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-tests-clean-ordered: sub-util-clean-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-tests-clean: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-tests-distclean-ordered: sub-util-distclean-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-tests-distclean: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-tests-install_subtargets-ordered: sub-util-install_subtargets-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-tests-install_subtargets: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-tests-uninstall_subtargets-ordered: sub-util-uninstall_subtargets-ordered  FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-tests-uninstall_subtargets: FORCE
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: opencl.pro C:/Qt/5.2.0/mingw48_32/mkspecs/win32-g++/qmake.conf C:/Qt/5.2.0/mingw48_32/mkspecs/features/spec_pre.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/qdevice.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/device_config.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/common/shell-win32.conf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/qconfig.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axbase.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axbase_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axserver.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_axserver_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_clucene_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_core_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_declarative.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_declarative_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_designer.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_designer_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_gui_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_help.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_help_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_multimedia.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_network_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_nfc_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_opengl.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_opengl_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_openglextensions.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_positioning_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qml.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qml_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qmltest.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_quick.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_quick_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_script.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_script_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_scripttools.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_sensors.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_sensors_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_serialport_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_sql_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_svg_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_uitools.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_uitools_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_webkit.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_webkit_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_winextras_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_xml_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/qt_functions.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/qt_config.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/win32-g++/qmake.conf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/spec_post.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/exclusive_builds.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/default_pre.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/win32/default_pre.prf \
		doc/doc.pri \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/resolve_config.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/default_post.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/win32/rtti.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/warn_on.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/win32/windows.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/testcase_targets.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/exceptions.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/yacc.prf \
		C:/Qt/5.2.0/mingw48_32/mkspecs/features/lex.prf \
		opencl.pro
	$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile opencl.pro
C:\Qt\5.2.0\mingw48_32\mkspecs\features\spec_pre.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\qdevice.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\device_config.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\common\shell-win32.conf:
C:\Qt\5.2.0\mingw48_32\mkspecs\qconfig.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_core.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_declarative.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_declarative_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_help.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_network.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_script.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_script_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_scripttools.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_scripttools_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_webkit.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_webkit_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_webkitwidgets.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\qt_functions.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\qt_config.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\win32-g++\qmake.conf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\spec_post.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\exclusive_builds.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\default_pre.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\win32\default_pre.prf:
doc\doc.pri:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\resolve_config.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\default_post.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\win32\rtti.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\warn_on.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\win32\windows.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\testcase_targets.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\exceptions.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\yacc.prf:
C:\Qt\5.2.0\mingw48_32\mkspecs\features\lex.prf:
opencl.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile opencl.pro

qmake_all: sub-src-qmake_all sub-examples-qmake_all sub-demos-qmake_all sub-util-qmake_all sub-tests-qmake_all FORCE

make_first: sub-src-make_first-ordered sub-examples-make_first-ordered sub-demos-make_first-ordered sub-util-make_first-ordered sub-tests-make_first-ordered FORCE
all: sub-src-all-ordered sub-examples-all-ordered sub-demos-all-ordered sub-util-all-ordered sub-tests-all-ordered FORCE
clean: sub-src-clean-ordered sub-examples-clean-ordered sub-demos-clean-ordered sub-util-clean-ordered sub-tests-clean-ordered FORCE
distclean: sub-src-distclean-ordered sub-examples-distclean-ordered sub-demos-distclean-ordered sub-util-distclean-ordered sub-tests-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets-ordered sub-examples-install_subtargets-ordered sub-demos-install_subtargets-ordered sub-util-install_subtargets-ordered sub-tests-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered sub-examples-uninstall_subtargets-ordered sub-demos-uninstall_subtargets-ordered sub-util-uninstall_subtargets-ordered sub-tests-uninstall_subtargets-ordered FORCE

docs:
	(set TOPSRC=D:/Suli/new/szakdoga/qtopencl-qt5.2/doc/..&set DESTDIR=D:/Suli/new/szakdoga/qtopencl-qt5.2/doc/html&qdoc3 -online D:/Suli/new/szakdoga/qtopencl-qt5.2/doc/src/qtopencl.qdocconf)

sub-src-debug_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-examples-debug_ordered: sub-src-debug_ordered 
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-demos-debug_ordered: sub-examples-debug_ordered 
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-util-debug_ordered: sub-demos-debug_ordered 
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-tests-debug_ordered: sub-util-debug_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-src-debug_ordered sub-examples-debug_ordered sub-demos-debug_ordered sub-util-debug_ordered sub-tests-debug_ordered

sub-src-release_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-examples-release_ordered: sub-src-release_ordered 
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-demos-release_ordered: sub-examples-release_ordered 
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-util-release_ordered: sub-demos-release_ordered 
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-tests-release_ordered: sub-util-release_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
release: sub-src-release_ordered sub-examples-release_ordered sub-demos-release_ordered sub-util-release_ordered sub-tests-release_ordered

sub-src-check_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-examples-check_ordered: sub-src-check_ordered 
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\examples\examples.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-demos-check_ordered: sub-examples-check_ordered 
	@if not exist demos\ mkdir demos\ & if not exist demos\ exit 1
	cd demos\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\demos\demos.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-util-check_ordered: sub-demos-check_ordered 
	@if not exist util\ mkdir util\ & if not exist util\ exit 1
	cd util\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\util\util.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-tests-check_ordered: sub-util-check_ordered 
	@if not exist tests\ mkdir tests\ & if not exist tests\ exit 1
	cd tests\ && ( if not exist Makefile $(QMAKE) D:\Suli\new\szakdoga\qtopencl-qt5.2\tests\tests.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-src-check_ordered sub-examples-check_ordered sub-demos-check_ordered sub-util-check_ordered sub-tests-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

